// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package model

import (
	"time"
)

type PingLog struct {
	ID        int32
	Timestamp time.Time
	Status    bool
	LossRate  float64
}
